spring:
    datasource:
        url: jdbc:postgresql://localhost:7432/async
        username: postgres
        password: postgres
    r2dbc:
        url: r2dbc:pool:postgresql://localhost:7432/async
        username: postgres
        password: postgres
        pool:
            initial-size: 100
            max-size: 500
            max-idle-time: 30m
            validation-query: SELECT 1
